### ISSUE TITLE
ChinaPush.setOnClickNotification无法触发回调

### ISSUE THREAD

**Issue by nicelogic** [developerHUA/china_push#2]
**device: MI 11**
**flutter version: stable, 3.24.5**
error msg:

> V/XMPush-3546( 3546): [Tid:8849] [PushMessageHandler] -->onHandleIntent(): action=com.xiaomi.mipush.RECEIVE_MESSAGE V/XMPush-3546( 3546): [Tid:8849] receive an intent from server, action=com.xiaomi.mipush.RECEIVE_MESSAGE V/XMPush-3546( 3546): [Tid:8849] [processing a message, action=] SendMessage, hasNotified=true V/XMPush-3546( 3546): [Tid:8849] [receive a message, msgid=] scm71246733709728578ko, jobkey=scm71246733709728578ko, btn=0, typeId=null, hasNotified=true W/XMPush-3546( 3546): [Tid:8849] [MessageHandleService] begin execute onNotificationMessageClicked from　scm71246733709728578ko I/PushModule( 3546): onNotificationMessageClicked: title:Janus content : 1112 data : {"aps":{"sound":"default","alert":{"title":"Janus","subtitle":"","body":"1112"}},"event_data":"{\"Event\":\"message_message\",\"ChatId\":\"836801887-846227937\",\"ChatType\":\"p2p\",\"MessageId\":\"f722a23c-45e2-4f82-bca6-0380da9b1a47\"}"} I/PushModule( 3546): PushManager onOpenNotification PushInterface:com.huarenkeji.china_push.core.MiPushInterface data :{"aps":{"sound":"default","alert":{"title":"Janus","subtitle":"","body":"1112"}},"event_data":"{\"Event\":\"message_message\",\"ChatId\":\"836801887-846227937\",\"ChatType\":\"p2p\",\"MessageId\":\"f722a23c-45e2-4f82-bca6-0380da9b1a47\"}"} W/libc    ( 3546): Access denied finding property "vendor.display.enable_optimal_refresh_rate" W/com.luojm.app0( 3546): type=1400 audit(0.0:172487): avc:  denied  { read } for  name="u:object_r:vendor_display_prop:s0" dev="tmpfs" ino=13232 scontext=u:r:untrusted_app:s0:c23,c259,c512,c768 tcontext=u:object_r:vendor_display_prop:s0 tclass=file permissive=0 app=com.luojm.app0 V/XMPush-3546( 3546): [Tid:8849] MessageHandleService V/XMPush-3546( 3546): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: pool-7-thread-1 V/XMPush-3546( 3546): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:1493) V/XMPush-3546( 3546): 	at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:1109) V/XMPush-3546( 3546): 	at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:281) V/XMPush-3546( 3546): 	at io.flutter.embedding.engine.dart.DartExecutor$DefaultBinaryMessenger.send(DartExecutor.java:464) V/XMPush-3546( 3546): 	at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:217) V/XMPush-3546( 3546): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:117) V/XMPush-3546( 3546): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:102) V/XMPush-3546( 3546): 	at com.huarenkeji.china_push.ChinaPushHandler.onOpenNotification(ChinaPushHandler.java:112) V/XMPush-3546( 3546): 	at com.huarenkeji.china_push.PushManager.onOpenNotification(PushManager.java:155) V/XMPush-3546( 3546): 	at com.huarenkeji.china_push.receiver.MiPushMessageReceiver.onNotificationMessageClicked(MiPushMessageReceiver.java:23) V/XMPush-3546( 3546): 	at com.xiaomi.mipush.sdk.MessageHandleService.a(SourceFile:147) V/XMPush-3546( 3546): 	at com.xiaomi.mipush.sdk.PushMessageHandler.a(SourceFile:206) V/XMPush-3546( 3546): 	at com.xiaomi.mipush.sdk.PushMessageHandler.b(SourceFile:158) V/XMPush-3546( 3546): 	at com.xiaomi.mipush.sdk.PushMessageHandler$1.run(SourceFile:59) V/XMPush-3546( 3546): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1251) V/XMPush-3546( 3546): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:668) V/XMPush-3546( 3546): 	at java.lang.Thread.run(Thread.java:1012) E/OpenGLRenderer( 3546): Unable to match the desired swap behavior. D/VRI[NotificationClickedActivity]( 3546): vri.reportNextDraw android.view.ViewRootImpl.performTraversals:4360 android.view.ViewRootImpl.doTraversal:2989 android.view.ViewRootImpl$TraversalRunnable.run:10304 android.view.Choreographer$CallbackRecord.run:1594 android.view.Choreographer$CallbackRecord.run:1603  D/VRI[NotificationClickedActivity]( 3546): vri.Setup new sync=wmsSync-VRI[NotificationClickedActivity]#8 D/VRI[NotificationClickedActivity]( 3546): vri.reportDrawFinished

**V/XMPush-3546( 3546): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: pool-7-thread-1**

**Comment by nicelogic** [comment]
<img width="1281" alt="image" src="https://github.com/user-attachments/assets/039a483c-9512-408d-a94f-21b46dc56b9e">
上述修改可以解决我的问题
